# PREPARE ALL HOSTS

- hosts: kafka-single  
  vars_files:
    - vars/settings.yaml

  tasks:    
    - name: disable firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: false
        masked: no

    - name: Create group "{{ kafka_user }}" 
      group:
        name: "{{ kafka_user }}"
        state: present

    - name: Create user '{{ kafka_user }}'
      user:
        name: "{{ kafka_user }}"
        password: NOT_LOGGING_PASSWORD
        group: "{{ kafka_user }}"

    - name: 'Install unzip'
      yum:
        name: unzip
        state: latest
      become: yes

    - name: 'Install JVM: {{ jvm_package }}'
      yum:
        name: "{{ jvm_package }}" 
        state: latest
      become: yes 
    
    - name: "Create installation folder {{ kafka_install_package_host_folder }}"
      file:
        path: "{{ kafka_install_package_host_folder }}"
        state: directory
        mode: 0755
        group: "{{ kafka_user }}"
        owner: "{{ kafka_user }}" 
    
    - name: Copy kafka package to remote server
      copy: src={{kafka_install_package_source_folder}}/{{ kafka_install_package_name }} dest={{ kafka_install_package_host_folder }}
      become: yes

    - name: tar kafka package "{{ kafka_install_package_host_folder }}/{{ kafka_install_package_name }}"
      unarchive:
        src: "{{ kafka_install_package_host_folder }}/{{ kafka_install_package_name }}"
        dest: "{{ kafka_install_package_host_folder }}"      
        remote_src: yes
        list_files: yes
      register: unarchived_list