kafka_user: kafka
jvm_package: java-11-openjdk-devel

#temporary folder to copy the install package in the host.
kafka_install_package_source_folder: /apps

#KAFKA Folder
kafka_folder_name: kafka
kafka_install_package_host_folder: /apps

#Source 
kafka_install_package_folder_name: kafka_2.13-3.1.0
kafka_install_package_name: kafka_2.13-3.1.0.tgz

#ZOOKEEPER Zookeeper.properties
zookeeper_data_dir: /apps/zookeeper-log
zookeeper_port: 2181
zookeeper_init_limit: 5
zookeeper_sync_limit: 2

# KAFKA server.properties [1]
# Commom properties with default values
kafka_log_dirs: /apps/kafka-log
kafka_listeners_port: 9092
kafka_advertised_listeners:
kafka_num_network_threads: 3
kafka_num_io_threads: 8
kafka_num_partitions: 3
kafka_offsets_topic_replication_factor: 1
kafka_transaction_tate_log_replication_factor: 1
kafka_transaction_state_log_min_isr: 1
kafka_log_retention_hours: 24
kafka_log_segment_bytes: 1073741824
kafka_log_retention_check_interval_ms: 300000
kafka_zookeeper_connection_timeout_ms: 6000
kafka_group_initial_rebalance_delay_ms: 0
kafka_socket_send_buffer_bytes: 102400
kafka_socket_receive_buffer_bytes: 102400
kafka_socket_request_max_bytes: 104857600