source_connection_url: jdbc:mysql://45.77.252.52:3306/employeemanager?user=username&password=password
directory_curl_template_j2: /apps/kafka-ansible/playbooks/bodyjsonforcurl
kafka_connector_server: 192.168.56.113
kafka_connector_port: 8083
source_connector_mode: bulk
topic_prefix: common.source.
key_converter_schema_registry_url: http://192.168.56.113:8081
value_converter_schema_registry_url: http://192.168.56.113:8081
batch_size: 10000
acks: -1