- hosts: testmyserver 
  vars_files:
    - ../vars/single/settings.yaml

  tasks:
    - name: Create Connector (uri)
      uri:
        url: "http://192.168.56.113:8083/connectors"
        headers:
          Content-Type: "application/json"
        method: POST
        body: "{{ lookup('file', 'test.json' ) }}"
        body_format: json
        validate_certs: no
        status_code: [201, 201, 204]
        headers:
          Content-Type: application/json
        # If you're interested in the response
        return_content: yes
      # register: api_result
      run_once: yes
  # - name: First task (uri)
  #     uri:
    #All Source
    #Ad1Partner
    #Ad1Dispatcher
    #Ad1Survey
    #Ad1Credit
    #Ad1Billing
    #Ad1Admin
    #Ad1ContactCenter (My Sql)
    #Ad1Sales (Custom Source and Sink)
    #Custom Source and Sink